server:
  servlet:
    context-path: /reg/system
  port: 8082
#环境
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml, classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 36000
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true

# oss对象存储设置
aliyun:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI5tCnt2p9soBmR61ury7v
  accessKeySecret: 9h1jLUh2cKUBVTZilkws5SP7beFkdC
  bucketName: reg-system-oss
  urlPrefix: http://reg-system-oss.oss-cn-beijing.aliyuncs.com/
##文件上传目录
#file.upload.url=D:/bs/reg-system-api/src/main/resources/file
